#!/bin/sh
cd ${0%/*} || exit 1

echo "----------------------------------"
echo "Cleaning working directory"
echo "Removing backup files"
find . \( -name core -o -name 'core.[1-9]*' \) -exec rm {} \;
find . \( -name '*.pvs' -o -name '*.OpenFOAM' \) -exec rm {} \;
rm logs testLoopReport > /dev/null 2>&1

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
echo "----------------------------------"